from numpy import*
from Lineal import gaussidel
a=array([[5,-3,1],[2,4,-1],[2,-3,8,]], float)
b=array([[5],[6],[4]], float)
x=array([[1],[1],[1]], float)
x=gaussidel(a,b,x)
print(x)
print("")
x=gaussidel(a,b,x)
print(x)
print("")
x=gaussidel(a,b,x)
print(x)
print("")
x=gaussidel(a,b,x)
print(x)
print("")
x=gaussidel(a,b,x)
print(x)
print("")
